INSERT INTO tb_usuario(nome, email, senha) VALUES ('Maria Antonia', 'mariaantonia@gmail.com', '8495621#a')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Joao Carlos da Silva', 'joaocarlos@gmail.com', '614564.4.g')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Marcos Pereira', 'marcospereira@outlook.com', '9948484a3.$')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Henrique de Moraes', 'henriquemoraes@bol.com', 'A1166514a%14')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Marcia Brugnolli', 'marciab@yahoo.com', '24989824God.')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Marta Ferrari', 'martaferrari@hotmail.com', '98429084Mar&&')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Victor Machado', 'victorm@gmail.com', '98984299Vm.')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Jonathan da Silva', 'jdasilva@gmail.com', '6456561t%V')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Patrick Moreira', 'patrickm@gmail.com', '89567923.aBc')
INSERT INTO tb_usuario(nome, email, senha) VALUES ('Fernanda de Cassia', 'fernandac@gmail.com', '561125433Tt~~')